### ISSUE TITLE
Per cluster namespaces in capi mgmt cluster

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#228]
It is best practice to have per cluster namespaces for the CRs in the capi cluster, which we are not currently following in the reference implementation.

**Comment by garloff** [comment]
Need expertise from @batistein

**Comment by batistein** [comment]
There are several reasons why each cluster should have its own namespace:
* clusterctl move - moves all resources from one namespace, not per cluster.
* Each cluster must have its own IaaS secret instead of sharing the configuration - this way each cluster manifest would include everything that' s good for GitOps
* Namespace separation is better for working with RBAC. You can easily give someone access (or read-only access for monitoring) by using the namespace

**Comment by fdobrovolny** [comment]
As the upcoming sprint draws near, here's a status update:

I've successfully developed a working solution for creating a default cluster within its designated namespace. At the moment, my focus is on adapting and thoroughly testing the feature by working through the scripts located in the bin folder.
