### ISSUE TITLE
capo-controller rejecting regiocloud API (Openstack API secured with Let's Encrypt cert)

### ISSUE THREAD

**Issue by mxmxchere** [SovereignCloudStack/k8s-cluster-api-provider#478]
When creating a  cluster using `make create` the capo-controller-manager refuses to communicate with the regiocloud API because it does not know the used CA (Let's Encrypt):

Log from capo-controller
```
E0731 10:36:29.563316       1 controller.go:326] "Reconciler error" err="providerClient authentication err: Get \"https://keystone.services.a.regiocloud.tech/\": x509: certi
ficate signed by unknown authority" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" OpenStackMachine="defau
lt/capi-testcluster-md-0-genw01-hgfx7" namespace="default" name="capi-testcluster-md-0-genw01-hgfx7" reconcileID=e27f81d7-9326-43d5-a0b0-e8b312a189a6
```

Regioclouds API is secured/signed via letsencrypt:
```
$ openssl s_client -connect keystone.services.a.regiocloud.tech:443
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = a.regiocloud.tech
verify return:1
---
Certificate chain
 0 s:CN = a.regiocloud.tech
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: id-ecPublicKey, 256 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jun 26 08:48:15 2023 GMT; NotAfter: Sep 24 08:48:14 2023 GMT
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 20 19:14:03 2021 GMT; NotAfter: Sep 30 18:14:03 2024 GMT

```

After patching the `secret/testcluster-cloud-config` with the letsencrypt CA the capo-controller stops complaining and creates the requested infrastructure:

To patch the secret i used the following command:

`kubectl patch secret testcluster-cloud-config  -p="{\"data\": {\"cacert\": \"$(cat /etc/ssl/certs/ISRG_Root_X1.pem |base64 -w0)\"}}"`

**Comment by chess-knight** [comment]
Hello @mxmxchere,
See [clusterctl_template.sh](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/main/terraform/files/bin/clusterctl_template.sh#L45) where CA is encoded:
```bash
AUTH_URL=$(print-cloud.py | yq eval .clouds.${OS_CLOUD}.auth.auth_url -)
AUTH_URL_SHORT=$(echo "$AUTH_URL" | sed s'/https:\/\///' | sed s'/\/.*$//')
CERT_CERT=$(openssl s_client -connect "$AUTH_URL_SHORT" </dev/null 2>&1 | head -n 1 | sed s'/.*CN\ =\ //' | sed s'/\ /_/g' | sed s'/$/.pem/')
CLOUD_CA_ENC=$(base64 -w 0 /etc/ssl/certs/"$CERT_CERT")
```

According to your description, it should work:
```bash
# CERT_CERT
$ openssl s_client -connect keystone.services.a.regiocloud.tech:443 </dev/null 2>&1 | head -n 1 | sed s'/.*CN\ =\ //' | sed s'/\ /_/g' | sed s'/$/.pem/'
ISRG_Root_X1.pem
```

But, assuming from the log that your `auth_url` is `https://keystone.services.a.regiocloud.tech/`, it doesn't work:
```bash
# AUTH_URL_SHORT
$ echo "https://keystone.services.a.regiocloud.tech/" | sed s'/https:\/\///' | sed s'/\/.*$//'
keystone.services.a.regiocloud.tech
# CERT_CERT
$ openssl s_client -connect keystone.services.a.regiocloud.tech </dev/null 2>&1 | head -n 1 | sed s'/.*CN\ =\ //' | sed s'/\ /_/g' | sed s'/$/.pem/'
809BB049C07F0000:error:8000006F:system_library:BIO_connect:Connection_refused:../crypto/bio/bio_sock2.c:125:calling_connect().pem
```
It happens because there is a missing port `443`. This code works e.g. for the plusserver-gx-scs environment, where `auth_url` has port included `https://api.gx-scs.sovereignit.cloud:5000`. Except for regiocloud, it most likely works for all community scs environments according to this [clouds-public.yaml
](https://github.com/SovereignCloudStack/docs/blob/main/community/cloud-resources/clouds-public.yaml)

Probably adding **:443** to the auth_url will work as a temporary fix for now, but we will definitely need to fix this.

**Comment by mxmxchere** [comment]
Thanks for the analysis, i will write a fix :)
