### ISSUE TITLE
memory limits for kube-apiserver

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#516]
As an operator of k8s clusters, I want to avoid the kube-apiservers to eat all memory ending up killing etcd (or the entire node).

Adapted from random k8s tip from @horazont in today's community call.

Let's quickly check whether this is something that affects us and could be addressed easily.

**Comment by horazont** [comment]
To elaborate: We had a case where the API servers would be so overwhelmed by client requests that they would OOM on a 8GB control plane node rather quickly (between 30s and 90s). Without memory limits, it was a gamble whether it'd take down etcd or freeze the node so far that it makes no difference.

In such a situation, joining a new control plane node via kubeadm is nigh impossible, because it's likely that the checks kubeadm does will fail because one of the nodes is broken in one way or the other (e.g. kubeadm checks for etcd quorum).

When placing memory limits (~75% of node memory worked for us) on the API server, you may still run into a situation where one API server is killed while you try to join another, but etcd at least is stable; and requests to the API servers are likely to be retried anyway.
