### ISSUE TITLE
Convert terraform/files/template/clusterctl.yaml.tmpl to a helmchart

### ISSUE THREAD

**Issue by mxmxchere** [SovereignCloudStack/k8s-cluster-api-provider#666]
CAPI and CAPO are currently fed by the templated version of terraform/files/template/clusterctl.yaml.tmpl. This includes a clusterclass (and its referenced resources), a secret and a cluster. If the clusterclass resources where a helmchart already they would only need to be packed in an archive to build the cluster-class part of a cluster-stack. So i think it is worth to convert the clusterctl.yaml.tmpl here to helmchart. This files is templated a lot anyways so it would benefit from being converted into a helmchart. Right now the settings for the proxyserver or containerd settings for example are injected via yq. If this was a helmchart one could introduce a proper configuration variable and let helm do the templating.

The following 8 resources are currently templated by various components:
Everything within double curly brackets is defined in environment.tfvars

| Kind  | Name | Comment | Roughly transfered |
| ------------- | ------------- | ------------- | ------------- |
| Secret |  {{ testcluster_name }}-cloud-config| Possibly out of scope for this helmchart | ❌ |
| OpenStackMachineTemplate | {{ prefix }}-{{ testcluster_name }}-md-0-genw01 | | ✅ |
| OpenStackMachineTemplate | {{ prefix }}-{{ testcluster_name }}-control-plane-genc01 | | ✅ |
| OpenStackClusterTemplate | {{ testcluster_name }}| |✅ |
| KubeadmControlPlaneTemplate | {{ testcluster_name }}-control-plane-genc01| | ✅ |
| KubeadmConfigTemplate | {{ prefix }}-{{ testcluster_name }}-md-0-genw01| | ✅ |
| ClusterClass | {{ testcluster_name }}| | ✅ |
| Cluster| {{ testcluster_name }}|Possibly out of scope for this helmchart | ❌ |

Cluster is out of scope for this helmchart as this aims to deploy only the templates. To create a cluster from this template it is necessary to deploy one cluster resource per cluster.

Uncategorized thoughts:

Current cluster-template is mostly optimized to create only one cluster. For example, cloud config openstackservergroups are bound to the templates, thus this approach is not suitable to create different clusters for different customers who may have different OpenStack projects. Transferring the current manifests into a helm chart does not (yet) solve any of these shortcomings.

Already implemented:

- external_id
- dns_nameservers
- controller_flavor
- worker_flavor
- prefix
- testcluster_name
- node_cidr
- etcd_unsafe_fs
- http_proxy
- no_proxy
- containerd_registry_files
- etcd_defrag
- tweak_kubeapi_memlimit
- worker_machine_gen
- control_plane_machine_gen
- kubeapi_cidr
- security groups 

See branch [helmification](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/tree/helmification) for current state

**Comment by jschoone** [comment]
Hi, @mxmxchere thanks for the issue. Yes, this also what is needed for https://github.com/SovereignCloudStack/issues/issues/492

I think it is a really good idea to realize it in this repository as it lowers the gap between reference implementation v1 and v2 even more. The template can just be copied over the the Cluster Stack definition for Openstack then.

Btw: Since this is Issue **666** it not Helm, but **Hell**chart :smiling_imp:

**Comment by paulphys** [comment]
Started working on templating in
https://github.com/SovereignCloudStack/cluster-stacks-playground

**Comment by paulphys** [comment]
We moved the current clusterstack development state into https://github.com/SovereignCloudStack/cluster-stacks/tree/dev-stack1. There is also a test release that can be read by the operator https://github.com/SovereignCloudStack/cluster-stacks/releases/tag/openstack-scs-1-27-v1. Next up we will evaluate how to pass values into our chart.

**Comment by paulphys** [comment]
The majority of all templating of Cluster API resources that is done in this repo via various bash scripts can now be done via Helm using [this helmchart](https://github.com/SovereignCloudStack/cluster-stacks/tree/dev-stack1). The only resource exception is the Cluster resource, which is not meant to be applied alongside the ClusterClass, because one ClusterClass can be used by multiple clusters. The only variable exception is the templating of the k8s version, this has been completely left out because this should be set via the image in the future.
